name: configuring host
on push:
runs-on: self-hosted
  jobs:
  configuring_host:
    steps:
    - name: configuring host on control node
      run: |
        cd ~
        sudo chmod 0700 ~/etc/ansible/hosts
        sudo echo -e "this is a line" >> ~/etc/ansible/hosts
