name: configuring hosts on CN
on push:

jobs:
  add_host:
    runs-on: self-hosted
    steps:
    - run: |
        pwd
        cd /etc/
        pwd
        sudo vi /etc/ansible/hosts
        echo "webservers:" >> /etc/ansible/hosts
