name: configuring host
on:
  repository_dispatch:
  runs-on: self-hosted
  jobs:
  configuring_host:
      run: |
        cd ~
        sudo chmod 0700 ~/etc/ansible/hosts
        sudo echo -e "this is a line" >> ~/etc/ansible/hosts
