name: configuring host
on: push
runs-on: self-hosted

  jobs:
  configuring_host:
    steps:
    uses: ./.github/workflows/gitactions.yml
#       run: |
#         cd ~
#         sudo chmod 0700 ~/etc/ansible/hosts
#         sudo echo -e "this is a line" >> ~/etc/ansible/hosts
