name: configuring hosts on CN
on: workflow_call

jobs:
  add_host:
    runs-on: self-hosted
    steps:
    - run: |
        mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          
          shell: bash
            ssh -i $SSH_KEY $SSH_USER@$SSH_HOST
        run: 'hostname; exit'
