name: installing ansible via Github Actions
on: push  
jobs:
  reusing_install_ansible_workflow:
    uses: ./.github/workflows/installing_ansible.yml
    
  reusing_install_python_workflow:
    uses: ./.github/workflows/installing_python_on_managed_node.yml
    
  running_playbook:
    uses: ./.github/workflows/running_playbook.yml
