name: installing ansible via Github Actions
on: push  
jobs:
  install_ansible_workflow:
    uses: ./.github/workflows/installing_ansible.yml
    
  install_python_workflow:
    uses: ./.github/workflows/installing_python_on_managed_node.yml
    
#   adding_host:
#     needs: install_ansible_workflow
#     uses: ./.github/workflows/adding_host.yml
