name: installing ansible via Github Actions
on: push
jobs:
  installing_ansible:
    runs-on: self-hosted
    steps:
    - name: installing ansible via github actions
      run: |
        ls -al
        sudo python -m pip install ansible -y
