name: 📓 Work Flow - Github Actions
on:
  push:
    branches: [master, main]

jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
        
  install_ansible:
    uses: ./.github/workflows/installing_ansible.yml
    
  install_python:
    needs: install_ansible
    uses: ./.github/workflows/installing_python.yml
    
#   adding_host:
#     needs: install_ansible
#     uses: ./.github/workflows/adding_host.yml
