name: Work Flow - Github Actions
on:
  push:
    branches: [master, main]

jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        
  install_ansible_workflow:
    uses: ./.github/workflows/installing_ansible.yml
    
  install_python_workflow:
    uses: ./.github/workflows/installing_python_on_managed_node.yml
    
#   adding_host:
#     needs: install_ansible_workflow
#     uses: ./.github/workflows/adding_host.yml
