name: host config
on: workflow_call
    
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: self-hosted
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          
          shell: bash
            ssh -i $SSH_KEY $SSH_USER@$SSH_HOST
      - name: hostname
        run: 'hostname; exit'
