name: host config
on: workflow_call
    
jobs:
  add_host:
    runs-on: self-hosted
    steps:
    - run: |
        pwd
        cd /etc/
        pwd
        sudo vi /etc/ansible/hosts
        echo "mywebservers:" >> /etc/ansible/hosts
