name: installing python on managed node
on: workflow_call
jobs:
  installing_python:
     runs-on: [self-hosted, managed-node]
     steps:
     - name: installing python via github actions
       run: |
        sudo apt update
        sudo apt install python3 -y
