jobs:
  installing_ansible:
    runs-on: self-hosted
    steps:
    - name: installing ansible via github actions
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible -y
