name: installing python on managed node
on: workflow_call
jobs:
  installing_python:
     runs-on: [self-hosted, managed-node]
     steps:
     - name: installing python via github actions
       run: |
        cd ..
        cd ..
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:deadsnakes/ppa
        sudo apt install python3 -y
